[template]
src = "blackbox.yml.tmpl"
dest = "/etc/prometheus/blackbox.yml"
prefix = "/%%PROJECT%%/%%ARENA%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/bin/systemctl restart blackbox"
