[template]
src = "prometheus.yml.tmpl"
dest = "/etc/prometheus/config.yml"
prefix = "/%%PROJECT%%/%%ARENA%%"

uid = 0
gid = 0
mode = "0640"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/sbin/reload prometheus || /sbin/restart prometheus || /sbin/start prometheus"
